In [1]:
"""
from huggingface_hub import snapshot_download

# Download all repository contents into a clean local directory
repo_root_dir = snapshot_download(
    repo_id="smji/SVMA-dataset", 
    repo_type="dataset",
    local_dir="./SVMA_dataset_media"
)

print(f"🚀 Raw dataset successfully mirrored to: {repo_root_dir}")
"""

'\nfrom huggingface_hub import snapshot_download\n\n# Download all repository contents into a clean local directory\nrepo_root_dir = snapshot_download(\n    repo_id="smji/SVMA-dataset", \n    repo_type="dataset",\n    local_dir="./SVMA_dataset_media"\n)\n\nprint(f"🚀 Raw dataset successfully mirrored to: {repo_root_dir}")\n'

In [ ]:
MY_HF_TOKEN = "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"

In [ ]:
"""
source_file = os.path.join(main_path, file_name)
destination_path = os.path.join(violent_folder, file_name)

os.makedirs(violent_folder, exist_ok=True)
shutil.move(source_file, destination_path)

"""

In [1]:
import torch
import cv2
import numpy as np
import time

import os
from extraction.images import model_loader as image_model_loader
from extraction.audios import model_loader as audio_model_loader
from extraction.video_processing import extract_video_features_compressed_ms, extract_audio_waveform_from_video

from extraction.audios import audio_processor_from_numpy

In [2]:
from xd_violence_pipeline import XDViolenceExtractor

In [3]:
extractor = XDViolenceExtractor()
extractor.extract_and_save(violence_count=800, 
                           normal_count=160)

⏳ Loading transformer weights into active hardware space (MPS)...
✅ Transformers successfully cached.

📂 Processing category [VIOLENCE] out of: Fighting


[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fac300] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1192ee280] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fac300] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x11906d960] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x128252d90] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x31a8e8c70] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fac830] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x31a8e8c70] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fa0f80] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x3256fce70] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x128252d90] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1192ee280] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fac300] Referenced QT chapter tr

⏱️ [Fighting] Avg Video Speed: 0.5207s | Avg Audio Speed: 0.2873s
📂 Processing category [VIOLENCE] out of: Shooting


[mov,mp4,m4a,3gp,3g2,mj2 @ 0x128252d90] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x3204fb230] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1192ee280] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x320e68c70] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fa0f80] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1192ee280] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fa0f80] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x31a8e8c70] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1192ee280] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x11ff6eeb0] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x320e5f640] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x108fac830] Referenced QT chapter track not found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x11906d960] Referenced QT chapter tr

⏱️ [Shooting] Avg Video Speed: 0.4863s | Avg Audio Speed: 0.2893s
📂 Processing category [NORMAL] out of: Normal
⏱️ [Normal] Avg Video Speed: 0.5750s | Avg Audio Speed: 0.4325s

💾 Data arrays successfully compiled and saved to disk.


In [5]:
violence_visual_data = np.load('data/images/xd_violence/violence_visual_data.npy')
violence_audio_data = np.load('data/images/xd_violence/violence_audio_data.npy')
normal_visual_data = np.load('data/images/xd_violence/normal_visual_data.npy')
normal_audio_data = np.load('data/images/xd_violence/normal_audio_data.npy')

In [4]:
from sklearn.model_selection import train_test_split
from training.kfold_train import stratified_kfold_train_val

from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

from sklearn.metrics import confusion_matrix, classification_report

In [37]:
violence_labels = np.ones(len(violence_visual_data))
normal_labels = np.zeros(len(normal_visual_data))

violence_visual_data = np.array(violence_visual_data)
normal_visual_data = np.array(normal_visual_data)

In [38]:
x = np.concat([violence_visual_data, normal_visual_data])
y = np.concat([violence_labels, normal_labels])

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.2)

In [18]:
import mlflow
import mlflow.sklearn
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report, 
    confusion_matrix, 
    accuracy_score, 
    precision_score, 
    recall_score, 
    f1_score
)

def stratified_kfold_train_val_mlflow(folds, threshold, model_params, x_train, y_train):
    """
    Executes Stratified K-Fold CV and logs every fold as a nested child run in MLflow.
    Returns the mean aggregate metrics across all folds.
    """
    # Initialize the Scikit-Learn splitter
    skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=model_params["random_state"])
    
    # Storage arrays for summary calculations
    cv_precision = []
    cv_recall = []

    print(f"🔄 Starting {folds}-Fold Cross Validation Tracking...")

    for fold_idx, (train_idx, val_idx) in enumerate(skf.split(x_train, y_train)):
        # 🔥 THE SECRET: Start a nested child run dedicated to this single fold
        with mlflow.start_run(run_name=f"Fold_{fold_idx + 1}", nested=True):
            
            # Split the training matrix into fold splits
            X_tr, X_val = x_train[train_idx], x_train[val_idx]
            y_tr, y_val = y_train[train_idx], y_train[val_idx]
            
            # Re-instantiate a fresh clone of the model for this fold
            fold_model = LogisticRegression(
                penalty=model_params["penalty"],
                C=model_params["C"],
                solver=model_params["solver"],
                max_iter=model_params["max_iter"],
                random_state=model_params["random_state"],
                class_weight=model_params["class_weight"]
            )
            
            # Train model on fold subset
            fold_model.fit(X_tr, y_tr)
            
            # Evaluate on verification fold split
            probs = fold_model.predict_proba(X_val)[:, 1]
            preds = (probs >= threshold).astype(int)
            
            # Calculate metrics for this specific fold validation block
            fold_precision = precision_score(y_val, preds, average='binary')
            fold_recall = recall_score(y_val, preds, average='binary')
            
            # Log metrics straight to the child run panel
            mlflow.log_metric("fold_val_precision", fold_precision)
            mlflow.log_metric("fold_val_recall", fold_recall)
            
            # Keep historical arrays updated
            cv_precision.append(fold_precision)
            cv_recall.append(fold_recall)
            
            print(f"   ↳ Fold {fold_idx + 1} Complete | Val Precision: {fold_precision:.4f} | Val Recall: {fold_recall:.4f}")
            
    # Return aggregated cross-validation metrics back to the parent execution line
    return np.mean(cv_precision), np.mean(cv_recall)


In [19]:
# Initialize or connect to a local lightweight SQLite database fill
mlflow.set_tracking_uri("sqlite:////Users/ngurahbagus/Python/Stage 1/mlflow.db")

# 2. Declare your experiment name
mlflow.set_experiment("Multimodal Experiment 2: Logistic Regression Classifier for XD Violence Video Array")

# 2. Master Parameter Configuration Bundle
params = {
    "penalty": "l2",
    "C": 0.5,
    "solver": "liblinear",
    "max_iter": 1000,
    "random_state": 42,
    "class_weight": "balanced",
    "classification_threshold": 0.30,
    "k_folds": 5
}

# 3. Open the Parent Run Environment
with mlflow.start_run(run_name="logistic_regression_with_cv_tree"):
    
    # Log your configurations at the parent level
    mlflow.log_params(params)
    
    # ─── STEP A: RUN NESTED CROSS-VALIDATION ───
    # This runs the loop and writes child runs directly under this active context block
    mean_cv_precision, mean_cv_recall = stratified_kfold_train_val_mlflow(
        folds=params["k_folds"],
        threshold=params["classification_threshold"],
        model_params=params,
        x_train=x_train,
        y_train=y_train
    )
    
    # Save the cross-validation aggregate averages to your primary parent sheet tracking matrix
    mlflow.log_metric("cv_mean_precision", mean_cv_precision)
    mlflow.log_metric("cv_mean_recall", mean_cv_recall)

    # ─── STEP B: TRAIN SYSTEM-WIDE PRODUCTION CHECKPOINT ───
    print("\n⏳ Training production model on entire train split...")
    final_model = LogisticRegression(
        penalty=params["penalty"],
        C=params["C"],
        solver=params["solver"],
        max_iter=params["max_iter"],
        random_state=params["random_state"],
        class_weight=params["class_weight"]
    )
    final_model.fit(x_train, y_train)
    
    # Evaluate final hold-out test metrics
    test_probabilities = final_model.predict_proba(x_test)[:, 1]
    test_predictions = (test_probabilities >= params["classification_threshold"]).astype(int)

    # Calculate final performance metrics
    test_precision = precision_score(y_test, test_predictions, average='binary')
    test_recall = recall_score(y_test, test_predictions, average='binary')

    # Log clean columns to the main dashboard row entry
    mlflow.log_metric("final_test_precision", test_precision)
    mlflow.log_metric("final_test_recall", test_recall)

    # ─── STEP C: SAVE FINAL ARTIFACT CHECKPOINT ───
    mlflow.sklearn.log_model(final_model, artifact_path="final_production_head")

    # Notebook standard validation diagnostic blocks
    print("\n📊 Final Production Hold-Out Classification Report:")
    print(classification_report(y_test, test_predictions))
    print("📊 Confusion Matrix:")
    print(confusion_matrix(y_test, test_predictions))
    print(f"\n🚀 Complete cross-validation structure tree saved perfectly to MLflow!")

🔄 Starting 5-Fold Cross Validation Tracking...
   ↳ Fold 1 Complete | Val Precision: 0.9695 | Val Recall: 0.9769
   ↳ Fold 2 Complete | Val Precision: 0.9618 | Val Recall: 0.9692
   ↳ Fold 3 Complete | Val Precision: 0.9412 | Val Recall: 0.9846
   ↳ Fold 4 Complete | Val Precision: 0.9552 | Val Recall: 0.9846
   ↳ Fold 5 Complete | Val Precision: 0.9699 | Val Recall: 0.9923

⏳ Training production model on entire train split...


2026/06/15 17:02:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/15 17:02:24 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html



📊 Final Production Hold-Out Classification Report:
              precision    recall  f1-score   support

         0.0       0.87      0.81      0.84        42
         1.0       0.95      0.97      0.96       150

    accuracy                           0.93       192
   macro avg       0.91      0.89      0.90       192
weighted avg       0.93      0.93      0.93       192

📊 Confusion Matrix:
[[ 34   8]
 [  5 145]]

🚀 Complete cross-validation structure tree saved perfectly to MLflow!


In [23]:
log_reg = LogisticRegression(
    penalty='l2',          # Use L2 (Ridge) regularization
    C=0.5,                 # Slightly stronger regularization than default
    solver='liblinear',        # Standard efficient solver
    max_iter=1000,         # Increased to guarantee optimization convergence
    random_state=42,
    class_weight='balanced'
)
threshold = 0.33

log_reg.fit(x_train, y_train)
test_probabilities = log_reg.predict_proba(x_test)[:, 1]
predictions = (test_probabilities >= threshold).astype(int)

print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.88      0.83      0.85        42
         1.0       0.95      0.97      0.96       150

    accuracy                           0.94       192
   macro avg       0.91      0.90      0.91       192
weighted avg       0.94      0.94      0.94       192

[[ 35   7]
 [  5 145]]


In [40]:
log_reg = LogisticRegression(
    penalty='l2',          # Use L2 (Ridge) regularization
    C=0.5,                 # Slightly stronger regularization than default
    solver='liblinear',        # Standard efficient solver
    max_iter=1000,         # Increased to guarantee optimization convergence
    random_state=42,
    class_weight='balanced'
)
log_reg.fit(x_train, y_train)
y_pred = log_reg.predict(x_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.67      0.90      0.76        29
         1.0       0.98      0.92      0.95       163

    accuracy                           0.92       192
   macro avg       0.82      0.91      0.86       192
weighted avg       0.93      0.92      0.92       192

[[  2  27]
 [ 18 145]]


In [24]:
import joblib

joblib.dump(log_reg, open("modelling/model/violence-xd_violence-visual.jobllib", 'wb'))

In [25]:
violence_audio_data = np.array(violence_audio_data)
normal_audio_data = np.array(normal_audio_data)

In [26]:
x = np.concat([violence_audio_data, normal_audio_data])
y = np.concat([violence_labels, normal_labels])

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.2)

In [28]:
# Initialize or connect to a local lightweight SQLite database fill
mlflow.set_tracking_uri("sqlite:////Users/ngurahbagus/Python/Stage 1/mlflow.db")

# 2. Declare your experiment name
mlflow.set_experiment("Multimodal Experiment 2: Logistic Regression Classifier for XD Violence Video Array")

# 2. Master Parameter Configuration Bundle
params = {
    "penalty": "l2",
    "C": 0.5,
    "solver": "liblinear",
    "max_iter": 1000,
    "random_state": 42,
    "class_weight": "balanced",
    "classification_threshold": 0.30,
    "k_folds": 5
}

# 3. Open the Parent Run Environment
with mlflow.start_run(run_name="logistic_regression_with_cv_tree"):
    
    # Log your configurations at the parent level
    mlflow.log_params(params)
    
    # ─── STEP A: RUN NESTED CROSS-VALIDATION ───
    # This runs the loop and writes child runs directly under this active context block
    mean_cv_precision, mean_cv_recall = stratified_kfold_train_val_mlflow(
        folds=params["k_folds"],
        threshold=params["classification_threshold"],
        model_params=params,
        x_train=x_train,
        y_train=y_train
    )
    
    # Save the cross-validation aggregate averages to your primary parent sheet tracking matrix
    mlflow.log_metric("cv_mean_precision", mean_cv_precision)
    mlflow.log_metric("cv_mean_recall", mean_cv_recall)

    # ─── STEP B: TRAIN SYSTEM-WIDE PRODUCTION CHECKPOINT ───
    print("\n⏳ Training production model on entire train split...")
    final_model = LogisticRegression(
        penalty=params["penalty"],
        C=params["C"],
        solver=params["solver"],
        max_iter=params["max_iter"],
        random_state=params["random_state"],
        class_weight=params["class_weight"]
    )
    final_model.fit(x_train, y_train)
    
    # Evaluate final hold-out test metrics
    test_probabilities = final_model.predict_proba(x_test)[:, 1]
    test_predictions = (test_probabilities >= params["classification_threshold"]).astype(int)

    # Calculate final performance metrics
    test_precision = precision_score(y_test, test_predictions, average='binary')
    test_recall = recall_score(y_test, test_predictions, average='binary')

    # Log clean columns to the main dashboard row entry
    mlflow.log_metric("final_test_precision", test_precision)
    mlflow.log_metric("final_test_recall", test_recall)

    # ─── STEP C: SAVE FINAL ARTIFACT CHECKPOINT ───
    mlflow.sklearn.log_model(final_model, artifact_path="final_production_head")

    # Notebook standard validation diagnostic blocks
    print("\n📊 Final Production Hold-Out Classification Report:")
    print(classification_report(y_test, test_predictions))
    print("📊 Confusion Matrix:")
    print(confusion_matrix(y_test, test_predictions))
    print(f"\n🚀 Complete cross-validation structure tree saved perfectly to MLflow!")

2026/06/15 17:04:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/15 17:04:04 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html


🔄 Starting 5-Fold Cross Validation Tracking...
   ↳ Fold 1 Complete | Val Precision: 0.9160 | Val Recall: 0.9375
   ↳ Fold 2 Complete | Val Precision: 0.9380 | Val Recall: 0.9453
   ↳ Fold 3 Complete | Val Precision: 0.9091 | Val Recall: 0.9449
   ↳ Fold 4 Complete | Val Precision: 0.9113 | Val Recall: 0.8898
   ↳ Fold 5 Complete | Val Precision: 0.9016 | Val Recall: 0.8661

⏳ Training production model on entire train split...

📊 Final Production Hold-Out Classification Report:
              precision    recall  f1-score   support

         0.0       0.60      0.72      0.66        29
         1.0       0.95      0.91      0.93       163

    accuracy                           0.89       192
   macro avg       0.77      0.82      0.79       192
weighted avg       0.90      0.89      0.89       192

📊 Confusion Matrix:
[[ 21   8]
 [ 14 149]]

🚀 Complete cross-validation structure tree saved perfectly to MLflow!


In [34]:
log_reg = LogisticRegression(
    penalty='l2',          # Use L2 (Ridge) regularization
    C=0.5,                 # Slightly stronger regularization than default
    solver='liblinear',        # Standard efficient solver
    max_iter=1000,         # Increased to guarantee optimization convergence
    random_state=42,
    class_weight='balanced'
)
threshold = 0.23

log_reg.fit(x_train, y_train)
test_probabilities = log_reg.predict_proba(x_test)[:, 1]
predictions = (test_probabilities >= threshold).astype(int)

print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.65      0.45      0.53        29
         1.0       0.91      0.96      0.93       163

    accuracy                           0.88       192
   macro avg       0.78      0.70      0.73       192
weighted avg       0.87      0.88      0.87       192

[[ 13  16]
 [  7 156]]


In [36]:
log_reg = LogisticRegression(
    penalty='l2',          # Use L2 (Ridge) regularization
    C=0.5,                 # Slightly stronger regularization than default
    solver='liblinear',        # Standard efficient solver
    max_iter=1000,         # Increased to guarantee optimization convergence
    random_state=42,
    class_weight='balanced'
)
log_reg.fit(x_train, y_train)
y_pred = log_reg.predict(x_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.46      0.90      0.61        29
         1.0       0.98      0.82      0.89       163

    accuracy                           0.83       192
   macro avg       0.72      0.86      0.75       192
weighted avg       0.90      0.83      0.85       192

[[ 13  16]
 [  7 156]]


In [35]:
import joblib

joblib.dump(log_reg, open("modelling/model/violence-xd_violence-audio.jobllib", 'wb'))

In [29]:
import subprocess
import time
from IPython.display import display, HTML

# Launch the server silently
# Update your notebook launcher cell to this:
mlflow_process = subprocess.Popen(
    ["mlflow", "ui", "--backend-store-uri", "sqlite:///mlflow.db", "--port", "5000"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)
time.sleep(2)

# Generate a clean, bright clickable local hyperlink in your notebook stdout
display(HTML("""
    <div style="padding:10px; background-color:#e1f5fe; border-left:5px solid #03a9f4; border-radius:4px;">
        📊 <strong>MLflow Server Ready!</strong> <br>
        <a href="http://127.0.0.1:5000" target="_blank" style="color:#0288d1; font-weight:bold; text-decoration:underline;">
            Click here to open the Tracking UI Dashboard in a new browser tab
        </a>
    </div>
"""))

In [97]:
# Terminate the background MLflow server process to free up port 5000
try:
    mlflow_process.terminate()
    print("🛑 Background MLflow tracking server has been successfully shut down.")
except NameError:
    print("ℹ️ No active background server variable detected in this session memory.")

🛑 Background MLflow tracking server has been successfully shut down.
